name: rust

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# Add permissions for the GITHUB_TOKEN
permissions:
  contents: write  # Needed for pushing the badge to the repository

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Build
      run: cargo build --verbose
    - name: Run unit tests
      run: cargo test --verbose --test unit_tests
    - name: Run integration tests (mock server)
      run: cargo test --verbose --test integration_tests

  coverage:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository with necessary history for pushing changes
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history needed for proper git operations

      # Set up Rust toolchain
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Install cargo-tarpaulin
      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin

      # Run tests and generate coverage report
      - name: Run tests with coverage
        run: |
          # Run tarpaulin and save output to a file so we can parse it reliably
          cargo tarpaulin --out Xml --output-dir coverage | tee tarpaulin_output.txt
          # Extract coverage percentage using a more reliable method
          COVERAGE=$(grep -oP '\d+\.\d+(?=%)' tarpaulin_output.txt | head -1)
          # Format with percentage sign for badge
          echo "COVERAGE=${COVERAGE}%" >> $GITHUB_ENV

      # Create badges directory
      - name: Create badges directory
        run: mkdir -p .github/badges

      # Generate coverage badge
      - name: Generate coverage badge
        uses: emibcn/badge-action@v2
        with:
          label: 'Test Coverage'
          status: ${{ env.COVERAGE }}
          color: 'blue,555,daf'
          path: .github/badges/coverage.svg

      # Commit and push badge to repository
      - name: Commit badge
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Action"
          git add .github/badges/coverage.svg
          git commit -m "Update coverage badge" || echo "No changes to commit"
          # Use token authentication for push to solve permission issues
          git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:${GITHUB_REF#refs/heads/}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload coverage report as artifact
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/cobertura.xml
          
      # Upload coverage to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/cobertura.xml
          fail_ci_if_error: false
